# Generated by Django 3.2.9 on 2021-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('context', models.TextField()),
                ('doi', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('raw_value', models.CharField(max_length=100)),
                ('raw_unit', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('correctness', models.CharField(max_length=100)),
                ('random', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('value', models.FloatField(max_length=100)),
                ('num_records', models.FloatField()),
            ],
        ),
    ]
