# Generated by Django 3.2.9 on 2021-11-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64, verbose_name='model_name')),
                ('confidence', models.FloatField(verbose_name='confidence')),
                ('ques', models.CharField(max_length=100, verbose_name='ques')),
                ('context', models.TextField(verbose_name='context')),
                ('answer', models.CharField(default='none', max_length=100, verbose_name='answer')),
                ('score', models.FloatField(default=0, verbose_name='score')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
    ]
