# Generated by Django 3.2.9 on 2021-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryqa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='confidence',
            field=models.FloatField(verbose_name='input-score'),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.TextField(verbose_name='input_text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='model_name',
            field=models.CharField(max_length=64, verbose_name='select'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.CharField(max_length=100, verbose_name='input_question'),
        ),
    ]
