# Generated by Django 3.2.9 on 2021-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryqa', '0002_auto_20211203_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='model_name',
        ),
        migrations.AddField(
            model_name='question',
            name='select',
            field=models.CharField(choices=[('BatteryBERT', 'BatteryBERT'), ('BatterySciBERT', 'BatterySciBERT'), ('BatteryOnlyBERT', 'BatteryOnlyBERT')], default='BatteryBERT', max_length=20, verbose_name='Select a model to analyse:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='confidence',
            field=models.FloatField(verbose_name='Confidence score threshold:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques',
            field=models.CharField(max_length=100, verbose_name='Ask a question:'),
        ),
    ]
