# Generated by Django 3.2.9 on 2022-04-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryqa', '0003_auto_20211205_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
    ]
